### ISSUE TITLE
Smoothing blur

### ISSUE THREAD

**Issue by shlapkoff** [mob-sakai/StaticBluredScreen#2]
Hi, thank you for really good solution for blur on Unity UI.
But in your solution the blur is too hard and looks bad in comparison with the native iOS blur.
Is there any way to fix this?
I found this repository with "good" blur, but I don't know how to implement this in to your solution. 
https://github.com/Jam3/glsl-fast-gaussian-blur

**Comment by mob-sakai** [comment]
Hi, @shlapkoff.
Thank you for using this plugin.

Ah, we dropped the quality of the blur to reduce the processing load...
* Using reduction buffer.
* Not iterative blur

To apply a wide range of high-quality blur, iterative processing is necessary.
For the simplest implementation, change 'StaticBluredScreen.cs' as follows.

```csharp
[line: 74]
_buffer.Blit (s_CopyId, s_BlurId, s_MaterialBlur);
_buffer.Blit (s_BlurId, s_CopyId, s_MaterialBlur); // Add to iterate blur.
_buffer.Blit (s_CopyId, s_BlurId, s_MaterialBlur); // Add to iterate blur.
_buffer.Blit (s_BlurId, rtId);

[line: 145]
const int kDesamplingRate = 1; // Change to disable reduction buffer.

[line: 149]
const int kReductionBufferRate = 1; // Change to disable reduction buffer.
```

![image](https://user-images.githubusercontent.com/12690315/38019731-5ba5e7ce-32b3-11e8-8355-d6a0dbfaa489.png)

Note: This change increases the blurring processing load.
NOTE: This project is merged to [UIEffect](https://github.com/mob-sakai/UIEffect).

**Comment by mob-sakai** [comment]
We plan to set the iteration count of the blurring process in the future.
Thank you 😄

**Comment by shlapkoff** [comment]
It works!
Thanks for the help!

**Comment by mob-sakai** [comment]
Hi, @shlapkoff.

Iteration count has been supported in v0.3.0!

![image](https://user-images.githubusercontent.com/12690315/40522542-6fc60e1a-600c-11e8-8b22-9a41f21e8657.png)

By the way, this feature was merged from UIEffect.
If you are interested, please try using UIEffect as well :)
